### PR TITLE
Update rust-bitcoin to 0.25, elements to 0.13.0

### PR DESCRIPTION
**Pull request by fujicoin**
We suggest updating rust-bitcoin to version 0.24.0 of the original repository.

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
Why not 0.26?

**Comment by fujicoin** [comment]
Fixed an issue where liquid could not compile.
It was necessary to update elements to 0.13.0, but with this it was necessary to update bitcoin to 0.25.

File: src/daemon.rs [hunk 1]
```diff
@@ -550,7 +549,7 @@ impl Daemon {
                         "failed estimating fee for target {}: {:?}",
                         target, reply["errors"]
                     );
-                    return None;
+                    return Some((*target, -1_000f64));
```
Comment (shesek) [inline src/daemon.rs:552]: Did you intend to change this as part of this PR?

File: src/util/script.rs [hunk 2]
```diff
@@ -31,7 +31,7 @@ pub fn get_script_asm(script: &Script) -> String {
 pub fn get_innerscripts(txin: &TxIn, prevout: &TxOut) -> InnerScripts {
     // Wrapped redeemScript for P2SH spends
     let redeem_script = if prevout.script_pubkey.is_p2sh() {
-        if let Some(PushBytes(redeemscript)) = txin.script_sig.iter(true).last() {
+        if let Some(Ok(PushBytes(redeemscript))) = txin.script_sig.instructions_minimal().last() {
```
Comment (shesek) [inline src/util/script.rs:34]: Why `instructions_minimal`? This shouldn't be enforcing minimal pushes.

File: src/new_index/schema.rs [hunk 3]
```diff
@@ -1439,22 +1440,25 @@ impl TxHistoryRow {
     }
 
     fn prefix_height(code: u8, hash: &[u8], height: u32) -> Bytes {
-        bincode::config()
```
Comment (shesek) [inline src/new_index/schema.rs:1442]: This [was previously done](https://github.com/Blockstream/electrs/commit/51b2a8e655a95994d68157eadc5b8f180923ff27#diff-bc90c6e3075e12ca234e17791f751e2bf1ca9913295d3e3eb4c53cd885e7a032L26) and later [reverted](https://github.com/Blockstream/electrs/commit/5daf1e811af528d1d59f9fcf0de78ac371dd759a) because it was suspected to be related to a database issue we were experiencing. This is worth additional investigation, but shouldn't be part of this PR.

File: Cargo.toml [hunk 4]
```diff
@@ -74,13 +71,9 @@ lto = true
...
 codegen-units = 1
 
-[patch.crates-io.bitcoin]
-git = "https://github.com/blockstream/rust-bitcoin"
-rev = "0.23-electrs"
-
 [patch.crates-io.elements]
 git = "https://github.com/elementsproject/rust-elements"
-rev = "98e0c4ba1b55cd876d1d8bcff64bcf01c4c370b6"
+rev = "0.13.0"
```
Comment (shesek) [inline Cargo.toml]: Maybe use the crate now that the changes needed are released?

**Review by shesek — CHANGES_REQUESTED** [review]
Thanks @fujicoin! Upgrading rust-bitcoin and rust-elements is overdue.

I left a few comments. I'd also like to upgrade them to their latest versions, did you try that and run into any complications?

Will look into this myself soon if you won't beat me to it.

**Comment by fujicoin** [comment]
The latest TAG for rust-bitcoin is 0.25.2. So I think this update is OK. 
elements 0.13.0 specifies bitcoin  0.25 . The dependencies of TAG 0.14.0 and 0.15.0 are the same as 0.13.0. 
I haven't tried it, but I think it's possible to compile electrs with elements 0.15.0.

File: src/daemon.rs (hunk 1 above)
Comment (fujicoin) [reply src/daemon.rs:552]: If this is `None`, the electrum will disconnect the connection with the electrs.
Many altcoins like Fujicoin have few transactions so the fee estimate doesn't work. Electrum will set a minimum fee when a dummy negative answer is returned.
If it is desirable to expand esplora-electrs to altcoin, I think it is better to fix this.

File: src/new_index/schema.rs (hunk 3 above)
Comment (fujicoin) [reply src/new_index/schema.rs:1442]: Fixed a warning that bincode :: config () should not be used during compilation. It doesn't seem to be a problem to me, but check back for database issues.

File: Cargo.toml (hunk 4 above)
Comment (fujicoin) [reply Cargo.toml]: I think that's fine.

File: src/util/script.rs (hunk 2 above)
Comment (fujicoin) [reply src/util/script.rs:34]: `.iter (true)` will result in the following compilation error.
```
error [E0599]: no method named `iter` found for struct` bitcoin :: blockdata :: script :: Script` in the current scope
   -> src / util / script.rs: 34: 68
```

Comment (shesek) [reply src/util/script.rs:34]: There's an `instructions()` method too

Comment (fujicoin) [reply src/util/script.rs:34]: In the case of `txin.script_sig.iter (true)`, when you look at the corresponding function of bitcoin 0.23.0, `enforce_minimal:` is set to `true` :
https://github.com/rust-bitcoin/rust-bitcoin/blob/2cba81935d0210cc32d3bdbaf0470f69708c109d/src/blockdata/script.rs#L332

`pub fn iter` is obsolete in bitcoin 0.25.2. The alternative part is as follows.

https://github.com/rust-bitcoin/rust-bitcoin/blob/46fdee5d88714be9367c5457ee0ad448f3803d96/src/blockdata/script.rs#L392

It says `To force minimal pushes, use [instructions_minimal] .`. So isn't `txin.script_sig.instructions_minimal ()` correct?

**Comment by dr-orlovsky** [comment]
Just FYI, rust-bitcoin has 0.26 release already (a week ago)

**Comment by fujicoin** [comment]
confirmed. The rust-bitcoin is certainly set to TAG 0.26.0 on January 15th.
But don't use 0.26.0 !
This is because the liquid cannot be compiled because it is inconsistent with the depends of rust-elements.

**Comment by dr-orlovsky** [comment]
Ok, I heard they are working on updating liquid to 0.26 these days

File: Cargo.toml (hunk 4 above)
Comment (fujicoin) [reply Cargo.toml]: Changed to use crate elements.
In conclusion, you should use 0.13.0.
0.14.0 has not been released to crate.
The following error occurs in 0.15.0.
```
error[E0433]: failed to resolve: could not find `bitcoin_hashes` in `elements`
 --> src/elements/registry.rs:8:15
  |
8 | use elements::bitcoin_hashes::hex::FromHex;
  |               ^^^^^^^^^^^^^^ could not find `bitcoin_hashes` in `elements`
```

**Comment by fujicoin** [comment]
I think it is better to separate esplora-electrs for bitcoin and liquid because coding becomes complicated.

**Comment by shesek** [comment]
I created a branch with rust-elements v0.15 and rust-bitcoin v0.26 (or v0.25 for liquid mode): https://github.com/Blockstream/electrs/commits/202101-deps

This will soon be merged to master.

**Comment by fujicoin** [comment]
OK. Then I will close this PR.
